### ISSUE TITLE
How to change the batchsize for model

### ISSUE THREAD

**Issue by OBVIOUSDAWN** [zhihou7/VCL#9]
Thank you for your work. Sorry to interrupt. I tried to train your code on a single 1080 (12G) and the training stopped because of the following error.
```
`2022-05-16 20:09:46.768782: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:185 : Out of range: Read less bytes than requested
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 1349, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 1441, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: Read less bytes than requested
         [[{{node save_1/RestoreV2}}]]
         [[save_1/RestoreV2/_235]]
  (1) Out of range: Read less bytes than requested
         [[{{node save_1/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/Train_VCL_ResNet_VCOCO.py", line 115, in <module>
    sw.train_model(sess, args.max_iters)
  File "/root/autodl-tmp/VCL-master/tools/../lib/models/train_Solver_VCOCO_MultiGPU.py", line 153, in train_model
    self.from_snapshot(sess)
  File "/root/autodl-tmp/VCL-master/tools/../lib/models/train_Solver_VCOCO.py", line 170, in from_snapshot
    self.saver_restore.restore(sess, self.pretrained_model)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/training/saver.py", line 1289, in restore
    sess.run(self.saver_def.restore_op_name,
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 955, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 1179, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 1358, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: Read less bytes than requested
         [[node save_1/RestoreV2 (defined at /root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
         [[save_1/RestoreV2/_235]]
  (1) Out of range: Read less bytes than requested
         [[node save_1/RestoreV2 (defined at /root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save_1/RestoreV2':
  File "tools/Train_VCL_ResNet_VCOCO.py", line 115, in <module>
    sw.train_model(sess, args.max_iters)
  File "/root/autodl-tmp/VCL-master/tools/../lib/models/train_Solver_VCOCO_MultiGPU.py", line 153, in train_model
    self.from_snapshot(sess)
  File "/root/autodl-tmp/VCL-master/tools/../lib/models/train_Solver_VCOCO.py", line 169, in from_snapshot
    self.saver_restore = tf.train.Saver(saver_t)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/training/saver.py", line 868, in _build
    self.saver_def = self._builder._build_internal(  # pylint: disable=protected-access
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/training/saver.py", line 507, in _build_internal
    restore_op = self._AddRestoreOps(filename_tensor, saveables,
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/training/saver.py", line 327, in _AddRestoreOps
    all_tensors = self.bulk_restore(filename_tensor, saveables, preferred_shard,
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1693, in restore_v2
    _, _, _op = _op_def_lib._apply_op_helper(
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/framework/op_def_library.py", line 792, in _apply_op_helper
    op = g.create_op(op_type_name, inputs, dtypes=None, name=scope,
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/util/deprecation.py", line 513, in new_func
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 3356, in create_op
    return self._create_op_internal(op_type, inputs, dtypes, input_types, name,
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 3418, in _create_op_internal
    ret = Operation(
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = `tf_stack.extract_stack()``
```
I have never used TensorFlow before and I wonder whether it is due to insufficient GPU memory, if so, how should I adjust batchsize, I did not find any place to adjust batchsize in the code. I would appreciate it if you could help me and look forward to your reply

**Comment by zhihou7** [comment]
Hi, 

>   File "/root/autodl-tmp/VCL-master/tools/../lib/models/train_Solver_VCOCO.py", line 170, in from_snapshot
    self.saver_restore.restore(sess, self.pretrained_model)

According to your error log, it might be because the pretrained model is corrupted.

As for how to change the batchsize, I set the batch size as 2 in VCL. Therefore, the code can not further reduce the batchsize. However, you can reduce the value of pos_augment and neg_augment during the training phase, and thus reduce the GPU memory requirements (Particularly, this strategy will affect the performance)

**Comment by OBVIOUSDAWN** [comment]
> Hi,
> 
> > File "/root/autodl-tmp/VCL-master/tools/../lib/models/train_Solver_VCOCO.py", line 170, in from_snapshot
> > self.saver_restore.restore(sess, self.pretrained_model)
> 
> According to your error log, it might be because the pretrained model is corrupted.
> 
> As for how to change the batchsize, I set the batch size as 2 in VCL. Therefore, the code can not further reduce the batchsize. However, you can reduce the value of pos_augment and neg_augment during the training phase, and thus reduce the GPU memory requirements (Particularly, this strategy will affect the performance)

I'm sorry to interrupt again. I tried downloading the weights 6 times and checked the md5 code of the downloaded files and found that the md5 code of the res50_faster_rcnn_iter_1190000.ckpt.data-00000-of-00001 file is different each time and the other two files are the same. And each of these 6 weight files have the same error and appear on two different servers. I try to use the weight in DRG code, but it also can't train, while the previous DRG can train normally. Can I train this model without using pre-trained weights? Or can you share the pre-trained weights? Thank you for your help and sorry to bother you again.

**Comment by zhihou7** [comment]
Here is the pre-trained weights in cloudstor: https://cloudstor.aarnet.edu.au/plus/s/4S80YZgbqCc8yuT 

Md5sum: ce33db09a798b4bacf22cc645fd27593

Feel free to ask me if you have further questions.

Regards,

**Comment by OBVIOUSDAWN** [comment]
> Here is the pre-trained weights in cloudstor: https://cloudstor.aarnet.edu.au/plus/s/4S80YZgbqCc8yuT
> 
> Md5sum: ce33db09a798b4bacf22cc645fd27593
> 
> Feel free to ask me if you have further questions.
> 
> Regards,

Thanks for your help, I downloaded the weights and found out that I have downloaded the wrong weights due to the network issue that caused res50_faster_rcnn_iter_1190000.ckpt.data-00000-of-00001 to become a 3kb file every time. The code is now ready to train properly, thank you very much for your help!
